name: 'analytics_chess'
version: '1.3.1'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
    analytics_chess:
        silver:
            game_header:
                materialized: view
                +schema: silver
        gold:
            dim_date:
                materialized: view
                +schema: gold
            dim_users:
                materialized: view
                +schema: gold
            dim_games:
                materialized: view
                +schema: gold
